import type { Metadata } from "next";
import Link from "next/link";
import { COMPANY } from "@/lib/company";
import { LEGAL_UPDATED_DATE, LEGAL_VERSIONS } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy — GameSignal",
  description: `Privacy information for GameSignal operated by ${COMPANY.legalName}`,
};

export default function PrivacyPage() {
  return (
    <main className="auth-page" style={{ alignItems: "flex-start", paddingTop: 48, paddingBottom: 64 }}>
      <article className="auth-card" style={{ width: "min(920px, 100%)", maxWidth: 920 }}>
        <Link href="/" className="brand">
          <span className="brand-mark" />
          <span>GameSignal</span>
        </Link>

        <div className="kicker" style={{ marginTop: 24 }}>Legal · closed beta</div>
        <h1>Privacy Policy</h1>
        <p>Last updated: {LEGAL_UPDATED_DATE} · Privacy version: {LEGAL_VERSIONS.privacy}</p>
        <p>
          This policy explains how personal data is handled in GameSignal. GameSignal is a product operated by {COMPANY.legalName}.
        </p>

        <h2>1. Data controller</h2>
        <p>
          The controller is <strong>{COMPANY.legalName}</strong>, {COMPANY.registeredAddress}. KRS {COMPANY.krs}, NIP {COMPANY.nip}, REGON {COMPANY.regon}.
        </p>
        <p>
          Privacy and support contact: <a href={`mailto:${COMPANY.supportEmail}`}>{COMPANY.supportEmail}</a>.
        </p>

        <h2>2. Data we process</h2>
        <p>Depending on how you use GameSignal, we may process:</p>
        <ul>
          <li>account data, such as email address, display name and authentication identifiers;</li>
          <li>workspace and monitoring configuration, including game titles, aliases, URLs and exclusion terms;</li>
          <li>billing choice information, including whether checkout was started as an individual or company/business;</li>
          <li>an auditable record of checkout statements accepted by the logged-in user, including the Terms/Privacy versions, recurring-billing acknowledgement, immediate-service request where applicable, selected plan/period, timestamp and associated Stripe Checkout Session identifier;</li>
          <li>where paid distance contracts apply, an immutable contract-confirmation record and delivery evidence intended to preserve the exact legal information supplied for that transaction;</li>
          <li>subscription and billing identifiers generated by Stripe. Stripe may also collect billing address, legal business name and VAT/tax ID where relevant. The closed beta currently uses Stripe sandbox and does not accept real payments;</li>
          <li>billing-ledger snapshots from Stripe invoices, including invoice identifiers and status, buyer type, billing country/address, customer name/email, tax IDs, currency, amounts, billing/service period and links to Stripe-hosted invoice documents;</li>
          <li>seller-side invoice/KSeF evidence where applicable, such as legal invoice number, KSeF session/invoice identifiers, KSeF number, submission status and UPO confirmation;</li>
          <li>an internal seller-side billing-account reference that links retained accounting evidence to Stripe customer/subscription identifiers without requiring the product workspace or login account to continue to exist;</li>
          <li>where needed for cross-border billing compliance, privacy-minimal country-level location evidence such as billing country, the country associated with the payment method, and/or country-level request geolocation. This evidence is used to identify matching, conflicting or insufficient location signals rather than to make an automatic tax decision;</li>
          <li>notification settings, including a Discord webhook if you choose to connect Discord;</li>
          <li>technical and security information needed to operate and protect the service, such as timestamps, request metadata, user-agent information and service logs;</li>
          <li>support and legal messages you send to us, including withdrawal, complaint or billing requests;</li>
          <li>publicly available creator and content metadata discovered through supported platforms, for example channel or creator names, video or stream titles, URLs, view counts and live viewer counts.</li>
        </ul>
        <p>
          We do not receive or store full payment-card details. Payment details are handled by Stripe. The dedicated billing-location evidence ledger is designed not to retain raw IP addresses, card numbers, card fingerprints or card last-four values. Password handling is provided through Supabase Auth; GameSignal does not expose your password to workspace users or administrators.
        </p>

        <h2>3. Why we use the data and legal bases</h2>
        <ul>
          <li><strong>Providing the service and account:</strong> to create and operate your account, workspace, monitors, dashboard, subscriptions and settings. The legal basis is performance of a contract or steps taken at your request before entering a contract.</li>
          <li><strong>Billing and proof of checkout choices:</strong> to process the selected subscription, distinguish individual/company billing, document recurring-billing and immediate-service requests, provide/preserve required contract confirmation, maintain invoice/accounting records, retain proportionate country-level evidence needed for cross-border billing review, handle cancellation/refund/withdrawal/complaint requests and resolve disputes. The legal bases are performance of the contract, legal obligations and our legitimate interest in maintaining reliable transaction records and defending legal claims.</li>
          <li><strong>Security, abuse prevention and support:</strong> to protect accounts, diagnose problems and respond to support requests. The legal basis is our legitimate interest in operating a secure and reliable service.</li>
          <li><strong>Creator-signal monitoring:</strong> to identify public mentions of monitored games and present those signals to the relevant workspace. The legal basis is our legitimate interest in providing creator-intelligence monitoring from publicly available sources.</li>
          <li><strong>Legal and accounting duties:</strong> where applicable, to comply with tax, accounting, KSeF, consumer-protection and other legal obligations. Real paid billing is not yet enabled in the closed beta.</li>
          <li><strong>Consent:</strong> where we specifically ask for consent for a separate purpose.</li>
        </ul>

        <h2>4. Data required to use the service</h2>
        <p>
          Some data is necessary to create an account or perform the contract, for example an email address and the information required for the selected monitoring configuration. If required account or service information is not provided, we may be unable to create the account or provide the requested feature.
        </p>
        <p>
          Billing information required by Stripe, tax law or the selected Individual/Company route must be provided to complete paid checkout. For a Company purchase this can include legal business identity, billing address and a supported tax identifier. If required billing, tax or contract-confirmation delivery information is missing or cannot be verified, paid checkout or paid access may be blocked until the requirement is satisfied.
        </p>

        <h2>5. Service providers, recipients and external platforms</h2>
        <p>
          We use specialist providers to operate GameSignal. These may include Supabase for database and authentication infrastructure, Vercel for application hosting, Stripe for billing infrastructure, and Resend for transactional/email-delivery infrastructure. Discord receives notifications only if you configure a Discord webhook.
        </p>
        <p>
          Where legally required for invoicing or tax compliance, invoice and taxpayer data may be disclosed through KSeF or otherwise to the Polish Ministry of Finance, tax authorities or other competent public authorities. Professional advisers and service providers may also receive data where necessary for accounting, legal compliance, dispute handling or security, subject to applicable confidentiality and data-protection requirements.
        </p>
        <p>
          YouTube/Google and Twitch are external platforms and data sources used to discover public content. Their own terms and privacy rules also apply when you visit or interact with those services.
        </p>

        <h2>6. International processing</h2>
        <p>
          Some technology providers may process data outside Poland or the European Economic Area. Where required, transfers are handled using safeguards available under applicable data-protection law, such as adequacy decisions or standard contractual clauses used by the relevant provider.
        </p>

        <h2>7. Retention and account deletion</h2>
        <p>
          Account, authentication, owned workspace, monitoring configuration and related product data are generally kept while the account or workspace is active. When an account is eligible for permanent deletion, the product-deletion flow removes the login account and owned workspace data, subject to information that must still be retained for legal obligations, payment/accounting records, disputes, fraud/security prevention or backup lifecycles.
        </p>
        <p>
          Where billing, tax, accounting, consent, contract-confirmation, refund, dispute or similar transaction evidence must be retained after product-account deletion, GameSignal is designed to detach those retained records from the deleted Auth user and workspace and keep them in a separate seller-side billing archive. The archived record does not keep the deleted workspace active and is not used to restore access to GameSignal. It is retained only for applicable legal, tax, accounting, fraud-prevention or claims-defense purposes and should be deleted or further minimized when those purposes and required retention periods end.
        </p>
        <p>
          Checkout-consent evidence, immutable contract-confirmation/delivery evidence, invoice/KSeF snapshots, proportionate billing-location evidence and transaction-related records may therefore remain longer than the active GameSignal account. Public creator/content metadata is retained only as reasonably needed to provide and maintain GameSignal signal history while the relevant product data remains active.
        </p>

        <h2>8. Automated processing</h2>
        <p>
          GameSignal uses automation to scan supported platforms, calculate signal scores, apply plan limits, synchronize billing states and identify records that require tax/accounting review. These processes support operation of the service, but GameSignal does not currently use solely automated decision-making that is intended to produce legal effects concerning an individual or similarly significantly affect that individual within the meaning of Article 22 GDPR.
        </p>
        <p>
          Tax and compliance automation is deliberately fail-closed where evidence is insufficient or contradictory: the record is blocked or routed for review rather than automatically declaring a tax/legal conclusion from an unverified user choice.
        </p>

        <h2>9. Your rights</h2>
        <p>
          Subject to the GDPR and applicable law, you may have rights to access your data, correct it, request deletion or restriction, receive certain data in a portable format, and object to processing based on legitimate interests. Where processing is based on consent, you can withdraw that consent without affecting processing that took place before withdrawal.
        </p>
        <p>
          You can also lodge a complaint with the competent supervisory authority. In Poland this is the President of the Personal Data Protection Office (Prezes Urzędu Ochrony Danych Osobowych).
        </p>

        <h2>10. Cookies and local storage</h2>
        <p>
          GameSignal uses technical storage needed for authentication, session continuity and product operation. The closed beta does not intentionally deploy advertising cookies. If analytics or optional marketing technologies are introduced later, this policy and any required consent mechanism will be updated first.
        </p>

        <h2>11. Closed beta changes</h2>
        <p>
          GameSignal is still in closed beta. Features, providers and retention rules may evolve. Material changes to this policy will be reflected by updating this page and its revision date before they apply where required.
        </p>

        <div className="dashboard-actions" style={{ marginTop: 28 }}>
          <Link className="btn btn-primary" href="/">Back to GameSignal</Link>
          <Link className="btn btn-ghost" href="/terms">Terms</Link>
          <Link className="btn btn-ghost" href="/withdrawal">Withdrawal</Link>
        </div>
      </article>
    </main>
  );
}
