import type { Metadata } from "next";
import Link from "next/link";
import { COMPANY } from "@/lib/company";

export const metadata: Metadata = {
  title: "Privacy Policy — GameSignal",
  description: `Privacy information for GameSignal operated by ${COMPANY.legalName}.`,
};

const updated = "14 August 2026";

export default function PrivacyPage() {
  return (
    <main className="auth-page" style={{ alignItems: "flex-start", paddingTop: 48, paddingBottom: 64 }}>
      <article className="auth-card" style={{ width: "min(920px, 100%)", maxWidth: 920 }}>
        <Link href="/" className="brand">
          <span className="brand-mark" />
          <span>GameSignal</span>
        </Link>

        <div className="kicker" style={{ marginTop: 24 }}>Legal · closed beta</div>
        <h1>Privacy Policy</h1>
        <p>Last updated: {updated}</p>
        <p>
          This policy explains how personal data is handled in GameSignal. GameSignal is a product operated by {COMPANY.legalName}.
        </p>

        <h2>1. Data controller</h2>
        <p>
          The controller is <strong>{COMPANY.legalName}</strong>, {COMPANY.registeredAddress}. KRS {COMPANY.krs}, NIP {COMPANY.nip}, REGON {COMPANY.regon}.
        </p>
        <p>
          Privacy and support contact: <a href={`mailto:${COMPANY.supportEmail}`}>{COMPANY.supportEmail}</a>.
        </p>

        <h2>2. Data we process</h2>
        <p>Depending on how you use GameSignal, we may process:</p>
        <ul>
          <li>account data, such as email address, display name and authentication identifiers;</li>
          <li>workspace and monitoring configuration, including game titles, aliases, URLs and exclusion terms;</li>
          <li>billing choice information, including whether checkout was started as an individual or company/business;</li>
          <li>an auditable record of checkout statements accepted by the logged-in user, including the Terms/Privacy versions, recurring-billing acknowledgement, immediate-service request where applicable, selected plan/period, timestamp and associated Stripe Checkout Session identifier;</li>
          <li>subscription and billing identifiers generated by Stripe. Stripe may also collect billing address, legal business name and VAT/tax ID where relevant. The closed beta currently uses Stripe sandbox and does not accept real payments;</li>
          <li>billing-ledger snapshots from Stripe invoices, including invoice identifiers and status, buyer type, billing country/address, customer name/email, tax IDs, currency, amounts, billing/service period and links to Stripe-hosted invoice documents;</li>
          <li>where needed for cross-border billing compliance, privacy-minimal country-level location evidence such as billing country, the country associated with the payment method, and/or country-level request geolocation. This evidence is used to identify matching, conflicting or insufficient location signals rather than to make an automatic tax decision;</li>
          <li>notification settings, including a Discord webhook if you choose to connect Discord;</li>
          <li>technical and security information needed to operate and protect the service, such as timestamps, request metadata, user-agent information and service logs;</li>
          <li>support and legal messages you send to us, including withdrawal or billing requests;</li>
          <li>publicly available creator and content metadata discovered through supported platforms, for example channel or creator names, video or stream titles, URLs, view counts and live viewer counts.</li>
        </ul>
        <p>
          We do not receive or store full payment-card details. Payment details are handled by Stripe. The dedicated billing-location evidence ledger is designed not to retain raw IP addresses, card numbers, card fingerprints or card last-four values. Password handling is provided through Supabase Auth; GameSignal does not expose your password to workspace users or administrators.
        </p>

        <h2>3. Why we use the data</h2>
        <ul>
          <li><strong>Providing the service and account:</strong> to create and operate your account, workspace, monitors, dashboard, subscriptions and settings. The legal basis is performance of a contract or steps taken at your request before entering a contract.</li>
          <li><strong>Billing and proof of checkout choices:</strong> to process the selected subscription, distinguish individual/company billing, document recurring-billing and immediate-service requests, maintain invoice/accounting records, retain proportionate country-level evidence needed for cross-border billing review, handle cancellation/refund/withdrawal requests and resolve disputes. The legal bases are performance of the contract, legal obligations and our legitimate interest in maintaining reliable transaction records and defending legal claims.</li>
          <li><strong>Security, abuse prevention and support:</strong> to protect accounts, diagnose problems and respond to support requests. The legal basis is our legitimate interest in operating a secure and reliable service.</li>
          <li><strong>Creator-signal monitoring:</strong> to identify public mentions of monitored games and present those signals to the relevant workspace. The legal basis is our legitimate interest in providing creator-intelligence monitoring from publicly available sources.</li>
          <li><strong>Legal and accounting duties:</strong> where applicable, to comply with tax, accounting, consumer-protection and other legal obligations. Real paid billing is not yet enabled in the closed beta.</li>
          <li><strong>Consent:</strong> where we specifically ask for consent for a separate purpose.</li>
        </ul>

        <h2>4. Service providers and external platforms</h2>
        <p>
          We use specialist providers to operate GameSignal. These may include Supabase for database and authentication infrastructure, Vercel for application hosting, Stripe for billing infrastructure, and Resend for email-delivery infrastructure. Discord receives notifications only if you configure a Discord webhook.
        </p>
        <p>
          YouTube/Google and Twitch are external platforms and data sources used to discover public content. Their own terms and privacy rules also apply when you visit or interact with those services.
        </p>

        <h2>5. International processing</h2>
        <p>
          Some technology providers may process data outside Poland or the European Economic Area. Where required, transfers are handled using safeguards available under applicable data-protection law, such as adequacy decisions or standard contractual clauses used by the relevant provider.
        </p>

        <h2>6. Retention</h2>
        <p>
          Account and workspace data is generally kept while the account or workspace is active. Monitoring history is retained as needed to provide signal-history features. When an account is eligible for permanent deletion, the deletion flow removes account and owned workspace data subject to information that must be retained for legal obligations, payment/accounting records, disputes, fraud/security prevention or backup lifecycles.
        </p>
        <p>
          Checkout-consent evidence, invoice snapshots, proportionate billing-location evidence and transaction-related records may be retained longer than the active account where reasonably necessary to meet legal, tax, accounting or claims-defense obligations. Public creator/content metadata is retained only as reasonably needed to provide and maintain GameSignal signal history.
        </p>

        <h2>7. Your rights</h2>
        <p>
          Subject to the GDPR and applicable law, you may have rights to access your data, correct it, request deletion or restriction, receive certain data in a portable format, and object to processing based on legitimate interests. Where processing is based on consent, you can withdraw that consent without affecting processing that took place before withdrawal.
        </p>
        <p>
          You can also lodge a complaint with the competent supervisory authority. In Poland this is the President of the Personal Data Protection Office (Prezes Urzędu Ochrony Danych Osobowych).
        </p>

        <h2>8. Cookies and local storage</h2>
        <p>
          GameSignal uses technical storage needed for authentication, session continuity and product operation. The closed beta does not intentionally deploy advertising cookies. If analytics or optional marketing technologies are introduced later, this policy and any required consent mechanism will be updated first.
        </p>

        <h2>9. Closed beta changes</h2>
        <p>
          GameSignal is still in closed beta. Features, providers and retention rules may evolve. Material changes to this policy will be reflected by updating this page and its revision date before they apply where required.
        </p>

        <div className="dashboard-actions" style={{ marginTop: 28 }}>
          <Link className="btn btn-primary" href="/">Back to GameSignal</Link>
          <Link className="btn btn-ghost" href="/terms">Terms</Link>
          <Link className="btn btn-ghost" href="/withdrawal">Withdrawal</Link>
        </div>
      </article>
    </main>
  );
}
